-- CreateTable
CREATE TABLE "Estado" (
    "id" INT4 NOT NULL,
    "nome" STRING NOT NULL,

    CONSTRAINT "Estado_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Cidade" (
    "id" INT4 NOT NULL,
    "nome" STRING NOT NULL,
    "estado_id" INT4 NOT NULL,

    CONSTRAINT "Cidade_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Pessoa" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nome" STRING NOT NULL,
    "email" STRING NOT NULL,
    "endereco" STRING NOT NULL,
    "telefone" STRING NOT NULL,
    "data_nasc" TIMESTAMP(3) NOT NULL,
    "cpf" STRING NOT NULL,
    "cnis" STRING NOT NULL,
    "cidade_id" INT4 NOT NULL,

    CONSTRAINT "Pessoa_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Situacao" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nome" STRING NOT NULL,

    CONSTRAINT "Situacao_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Tipo" (
    "id" INT4 NOT NULL,
    "nome" STRING NOT NULL,

    CONSTRAINT "Tipo_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Especialista" (
    "id" INT4 NOT NULL,
    "nome" STRING NOT NULL,
    "email" STRING NOT NULL,
    "telefone" STRING NOT NULL,
    "endereco" STRING NOT NULL,

    CONSTRAINT "Especialista_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Beneficio" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "numero_beneficio" STRING NOT NULL,
    "situacao_id" INT4 NOT NULL,
    "pessoa_id" INT4 NOT NULL,
    "tipo_id" INT4 NOT NULL,
    "especialista_id" INT4 NOT NULL,

    CONSTRAINT "Beneficio_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Documentos" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "descricao" STRING NOT NULL,
    "imagem" STRING NOT NULL,
    "beneficio_id" INT4 NOT NULL,

    CONSTRAINT "Documentos_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TipoMovimentacao" (
    "id" INT4 NOT NULL,
    "nome" STRING NOT NULL,

    CONSTRAINT "TipoMovimentacao_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Movimentacao" (
    "id" INT4 NOT NULL,
    "beneficio_id" INT4 NOT NULL,
    "tipo_movimentacao_id" INT4 NOT NULL,

    CONSTRAINT "Movimentacao_pkey" PRIMARY KEY ("id")
);
